### ISSUE TITLE
BSD2_Header templates doesn't match opensource.org reference

### ISSUE THREAD

**Issue by crdelsey** [ament/ament_lint#109] opened 2018-09-27 00:38 UTC
The reference license at [opensource.org](https://opensource.org/licenses/BSD-3-Clause) uses the phrase COPYRIGHT *HOLDER* OR CONTRIBUTORS whereas the [license template]( https://github.com/ament/ament_lint/blob/master/ament_copyright/ament_copyright/template/bsd2_header.txt ) in the `ament_copyright` tool uses the phrase COPYRIGHT *OWNER* OR CONTRIBUTORS.

This will cause the copyright linter to fail any source using the standard license text.

**Comment by dirk-thomas** [comment] 2018-10-08 18:50
The current snippet matches the copyright notice present in several hundreds of files in ROS 2 (and 1) packages. So changing this from one to the other is not an option.

It would be great making the linter more flexible though to accept both variations. Any PR towards this would be highly appreciated.

**Comment by crdelsey** [comment] 2018-10-08 22:53
I kind of figured that would be the answer. I noticed that https://spdx.org lists the phrases of the licenses that are allowed to change while still being considered the same license. I figure that would be a good starting point.

**Comment by cottsay** [comment] 2019-07-23 15:01
Would it be acceptable to simply add another set of templates which matches the opensource.org phrasing and formatting?

The only other solutions I can see are either to curate a set of rules where phrases could change, or introduce an expression that we could embed within the templates that could match multiple wordings or phrases. Either solution sounds much more involved than just maintaining multiple forms as separate templates.

**Comment by dirk-thomas** [comment] 2019-07-23 16:12
> Would it be acceptable to simply add another set of templates which matches the opensource.org phrasing and formatting?

Sounds good to me too.

**Comment by crdelsey** [comment] 2019-07-23 21:10
I'm ok with that solution. I think I've got other license headers that will need more, but that's a separate issue.

**Comment by Blast545** [comment] 2020-01-29 18:31
#205 should close this issue

**Comment by tfoote** [comment] 2020-01-30 03:38
I would not close this with #205 but think that we should remove those entries. We should not have an unused license in our linters lest it be used by someone to make their linters pass. The original author doesn't know where it came from: https://github.com/ros2/geometry2/pull/222#issuecomment-579235662

**Comment by Blast545** [comment] 2020-01-30 13:13
@tfoote The problem is what dirk-thomas addressed some time ago:

> The current snippet matches the copyright notice present in several hundreds of files in ROS 2 (and 1) packages. So changing this from one to the other is not an option.

Removing that license would cause problems with old code, that's why the 'bsd2' license shouldn't be changed, and instead a new one was added.

**Closed** 2020-01-30 17:46 UTC
Labels: enhancement
