### ISSUE TITLE
ament_uncrustify formats messages with default values incorrenctly

### ISSUE THREAD

**Issue by esteve** [ament/ament_lint#74] opened 2017-05-04 09:39 UTC
Given the following message:

```
int16[2] value_a [1, 2]
int16[2] value_b [3, 4]
```

the C++ generator produces the following code:

```c++
...
  Various_()
  : value_a({{1, 2}}),
    value_b({{3, 4}})
  {
  }
...
```

however, `uncrustify` with https://github.com/ament/ament_lint/blob/master/ament_uncrustify/ament_uncrustify/configuration/ament_code_style.cfg reformats the generated code as:

```
6: --- /home/esteve/Projects/ros2_java/output/build_isolated_java/rosidl_generator_cpp/rosidl_generator_cpp/rosidl_generator_cpp/msg/various__struct.hpp
6: +++ /home/esteve/Projects/ros2_java/output/build_isolated_java/rosidl_generator_cpp/rosidl_generator_cpp/rosidl_generator_cpp/msg/various__struct.hpp.uncrustify
6: @@ -41,2 +41 @@
6: -    value_b({{3, 4}})
6: -  {
6: +    value_b({{3, 4}}) {
6:
6: 1 files with code style divergence
```

which causes `ament_uncrustify` to fail.

**Comment by wjwwood** [comment] 2017-05-05 00:47
@esteve what lead you to notice this? @mikaelarguedas or @dirk-thomas are we running uncrustify on our generated code by default?

**Comment by dirk-thomas** [comment] 2017-05-05 04:00
Yes, when being explicitly requested (https://github.com/ros2/rosidl/blob/69400938eef1f6886fd65951d18fae7d3780e47d/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake#L36-L38) the generators add linters e.g. (https://github.com/ros2/rosidl/blob/master/rosidl_generator_cpp/cmake/rosidl_generator_cpp_generate_interfaces.cmake#L121-L144).

**Comment by esteve** [comment] 2017-05-05 07:06
@wjwwood this branch (https://github.com/esteve/rosidl/tree/linter-errors) adds a message like the one in the issue description and activates linters to show that the generated message does not pass `ament_uncrustify`

**Comment by dirk-thomas** [comment] 2017-05-08 18:42
The current configuration file for uncrustify actually configures the style checked exactly in the way the code generator generates the code:

```
Various_()
: value_a({{1, 2}}),
  value_b({{3, 4}})
{
}
```

Maybe you can try a similar example but with a different initialization / types. If that passes this may be a bug in `uncrustify` which gets confused by the `{{` and `}}` from the initialization arguments. You might want to report this upstream with an example.

**Comment by esteve** [comment] 2017-05-08 18:49
@dirk-thomas yeah, the uncrustify configuration seems to be fine, but it doesn't seem to work, at least on my workspace. Have you tried the branch I pushed? https://github.com/esteve/rosidl/tree/linter-errors

**Comment by dirk-thomas** [comment] 2017-05-08 18:51
> Have you tried the branch I pushed?

No, I haven't.

**Comment by esteve** [comment] 2017-05-08 18:58
> No, I haven't.

Will you then?

**Comment by esteve** [comment] 2017-05-08 19:11
@dirk-thomas BTW, I took the time to back the claims of this issue with proof, so your statement doesn't seem to be entirely factual:

> The current configuration file for uncrustify actually configures the style checked exactly in the way the code generator generates the code

**Comment by dirk-thomas** [comment] 2017-05-08 19:13
> Will you then?

I do believe your posted result. That `uncrustify` complains about the generated code. But since we pass the "correct" configuration to `uncrusitfy` (which works in similar examples as intended, please see plenty of existing code which uses the same style and passes the linter) there is not much we can do about it (except marking the lines in the code generation step to be ignored by uncustify or fixing the problem upstream in uncrustify).

Since I don't see what I would gain by testing your branch (I would expect to see exactly the result you posted) I am not sure why I should do that?

**Comment by esteve** [comment] 2017-05-09 10:18
> I do believe your posted result.

From your previous comment, where you pasted a snippet formatted according the style configuration, one could assume that it was generated by actually running uncrustify. So I wonder what was the point of posting that handcrafted snippet at all if I already had showed that it wasn't the expected result.

Anyway, we seem to agree that there may be an issue in uncrustify, so I filed a ticket detailing the issue: https://github.com/uncrustify/uncrustify/issues/1142

**Comment by mikaelarguedas** [comment] 2017-08-03 22:32
waiting for the bug to be addressed upstream

**Comment by dirk-thomas** [comment] 2018-02-22 22:28
I will close this since the issue is tracked upstream. Keeping this open doesn't seem to provide a significant "visibility" advantage.

**Closed by dirk-thomas** 2018-02-22 22:28 UTC
Labels: bug, duplicate
